version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable

environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

jobs:
  Build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: mvn clean verify
        
