version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable

environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      
orbs:
  maven: circleci/maven@0.0.12 

jobs:
  Build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: ./mvnw test verify
      
workflows:
  version: 2
  deploy:
    jobs:
      - Build:
          context: MobiquityContext
          filters:
            branches:
              only: main
