build:
    working_directory: ~/entity-cooking
    parallelism: 1
    shell: /bin/bash --login

    docker:
     - image: circleci/openjdk:8-jdk-browsers
     
     environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    steps:
      - checkout
#      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: mvn package
